In [2]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import os
import cv2
%matplotlib inline

from tensorflow.keras import layers
from tensorflow import keras

In [7]:
y = os.listdir('./완료1')

In [8]:
i = 0
while(i<50):
    y[i] = y[i].split('.')[0]
    i = i + 1

In [9]:
os.listdir('./완료1')

['AI스피커',
 'DSLR',
 'led마스크',
 'TV',
 '갤럭시버즈',
 '갤럭시폰',
 '고데기',
 '공기청정기',
 '그래픽카드',
 '냉장고',
 '노트북',
 '닌텐도스위치',
 '다리미',
 '라디오',
 '마사지건',
 '마우스',
 '마이크',
 '모니터',
 '믹서기',
 '블루투스 스피커',
 '서큘레이터',
 '스마트밴드',
 '스탠드',
 '스탠드에어컨',
 '아이폰',
 '안마의자',
 '액션캠',
 '앰프',
 '에어랩',
 '에어팟',
 '에어프라이어',
 '오븐',
 '웹캠',
 '인덕션',
 '전기면도기',
 '전기밥솥',
 '전기장판',
 '전기포트',
 '전자드럼',
 '전자피아노',
 '청소기',
 '카메라',
 '카메라렌즈',
 '커피머신',
 '키보드',
 '튀김기',
 '프로젝터',
 '프린터',
 '헤드셋',
 '헤어드라이기']

In [10]:
trainy = np.asarray(os.listdir('./완료1'))

In [11]:
trlabel = np.unique(trainy)

In [12]:
trlabel

array(['AI스피커', 'DSLR', 'TV', 'led마스크', '갤럭시버즈', '갤럭시폰', '고데기', '공기청정기',
       '그래픽카드', '냉장고', '노트북', '닌텐도스위치', '다리미', '라디오', '마사지건', '마우스',
       '마이크', '모니터', '믹서기', '블루투스 스피커', '서큘레이터', '스마트밴드', '스탠드', '스탠드에어컨',
       '아이폰', '안마의자', '액션캠', '앰프', '에어랩', '에어팟', '에어프라이어', '오븐', '웹캠',
       '인덕션', '전기면도기', '전기밥솥', '전기장판', '전기포트', '전자드럼', '전자피아노', '청소기',
       '카메라', '카메라렌즈', '커피머신', '키보드', '튀김기', '프로젝터', '프린터', '헤드셋',
       '헤어드라이기'], dtype='<U8')

In [13]:
trlabel[0]

'AI스피커'

In [14]:
train_data_paths = []
train_y = []
i = 0
for i in range(50):
    paths = tf.io.matching_files('./완료1/{}/*.png'.format(trlabel[i]))
    train_data_paths.append(paths)
    label_num = np.ones(len(paths)) * i
    train_y.append(label_num)


In [15]:
train_data_paths_1d = np.concatenate(train_data_paths, axis=0)

In [16]:
train_data_paths_1d

array([b'.\\\xec\x99\x84\xeb\xa3\x8c1\\AI\xec\x8a\xa4\xed\x94\xbc\xec\xbb\xa4\\[\xed\x81\xac\xea\xb8\xb0\xeb\xb3\x80\xed\x99\x98]2.png',
       b'.\\\xec\x99\x84\xeb\xa3\x8c1\\AI\xec\x8a\xa4\xed\x94\xbc\xec\xbb\xa4\\[\xed\x81\xac\xea\xb8\xb0\xeb\xb3\x80\xed\x99\x98]GOOGLE_000000000007.png',
       b'.\\\xec\x99\x84\xeb\xa3\x8c1\\AI\xec\x8a\xa4\xed\x94\xbc\xec\xbb\xa4\\[\xed\x81\xac\xea\xb8\xb0\xeb\xb3\x80\xed\x99\x98]GOOGLE_000000000008.png',
       ...,
       b'.\\\xec\x99\x84\xeb\xa3\x8c1\\\xed\x97\xa4\xec\x96\xb4\xeb\x93\x9c\xeb\x9d\xbc\xec\x9d\xb4\xea\xb8\xb0\\[\xed\x81\xac\xea\xb8\xb0\xeb\xb3\x80\xed\x99\x98]naver_0344.png',
       b'.\\\xec\x99\x84\xeb\xa3\x8c1\\\xed\x97\xa4\xec\x96\xb4\xeb\x93\x9c\xeb\x9d\xbc\xec\x9d\xb4\xea\xb8\xb0\\[\xed\x81\xac\xea\xb8\xb0\xeb\xb3\x80\xed\x99\x98]naver_0345.png',
       b'.\\\xec\x99\x84\xeb\xa3\x8c1\\\xed\x97\xa4\xec\x96\xb4\xeb\x93\x9c\xeb\x9d\xbc\xec\x9d\xb4\xea\xb8\xb0\\[\xed\x81\xac\xea\xb8\xb0\xeb\xb3\x80\xed\x99\x98]naver_0346.png'],


In [17]:
train_y = np.concatenate(train_y)

In [18]:
train_y, train_y.shape

(array([ 0.,  0.,  0., ..., 49., 49., 49.]), (25000,))

In [19]:
def tf_read_image(path):
    gfile = tf.io.read_file(path)
    image = tf.io.decode_image(gfile, dtype = tf.float32) #float32로 dtype를 지정하면 0~1로 정규화되어서 읽음
    return image

In [20]:
def make_batch(batch_paths):
    batch_images = []
    for path in batch_paths:
        image = tf_read_image(path)
        batch_images.append(image)
    return tf.convert_to_tensor(batch_images)

In [21]:
train_x = make_batch(train_data_paths_1d)

In [17]:
train_x.shape, train_y.shape

(TensorShape([25000, 72, 72, 3]), (25000,))

In [18]:
train_x = train_x.numpy()

In [19]:
type(train_x), type(train_y)

(numpy.ndarray, numpy.ndarray)

In [20]:
input_shape = (72, 72, 3)
num_classes = 50

train_x = train_x

In [21]:
np.max(train_x), np.min(train_x)

(1.0, 0.0)

In [1]:
from tensorflow.keras.applications.xception import Xception

In [23]:
model= Xception()

In [33]:
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 72, 72, 3)]       0         
_________________________________________________________________
xception (Functional)        (None, 3, 3, 2048)        20861480  
_________________________________________________________________
global_average_pooling2d (Gl (None, 2048)              0         
_________________________________________________________________
dense (Dense)                (None, 1000)              2049000   
Total params: 22,910,480
Trainable params: 22,855,952
Non-trainable params: 54,528
_________________________________________________________________


In [24]:
model.compile(optimizer=tf.keras.optimizers.Adam(),
                      loss = 'sparse_categorical_crossentropy',
                      metrics=['accuracy'])

In [25]:
num_epochs = 10
batch_size = 100

hist = model.fit(train_x, train_y, batch_size=batch_size, shuffle=True, epochs=num_epochs)

Epoch 1/10
250/250 [==============================] - 33s 131ms/step - loss: 1.3567 - accuracy: 0.6572
Epoch 2/10
250/250 [==============================] - 33s 132ms/step - loss: 0.4698 - accuracy: 0.8589
Epoch 3/10
250/250 [==============================] - 33s 133ms/step - loss: 0.2985 - accuracy: 0.9069
Epoch 4/10
250/250 [==============================] - 33s 133ms/step - loss: 0.2136 - accuracy: 0.9319
Epoch 5/10
250/250 [==============================] - 33s 133ms/step - loss: 0.1660 - accuracy: 0.9469
Epoch 6/10
250/250 [==============================] - 33s 133ms/step - loss: 0.1478 - accuracy: 0.9535
Epoch 7/10
250/250 [==============================] - 33s 133ms/step - loss: 0.1283 - accuracy: 0.9600
Epoch 8/10
250/250 [==============================] - 33s 133ms/step - loss: 0.0992 - accuracy: 0.9696
Epoch 9/10
250/250 [==============================] - 33s 133ms/step - loss: 0.0983 - accuracy: 0.9688
Epoch 10/10
250/250 [==============================] - 34s 135ms/step - l

In [ ]:
result = np.argmax(pred, axis=1)

In [ ]:
result.shape, result

In [ ]:
test_y.shape, test_y

In [ ]:
count = 0
for index in range(len(test_y)):
    if result[index]!=test_y[index]:
        print('index,result, test_y', index, result[index], test_y[index])
        count += 1
print(count, 'error rate = ', count/len(test_y))

In [ ]:
accuracy = 1-count/len(test_y)
accuracy

In [ ]:
confirm = os.listdir('./완료/헤드셋')

In [ ]:
test_img = train_x[321]
pred = model.predict(test_img.reshape(1,72,72,3))

In [ ]:
def myResize(input_img, dst_size):
    out_imgs = []
    for img in input_img:
        img_out = cv2.resize(img, dsize=(dst_size, dst_size), interpolation=cv2.INTER_LINEAR)
        out_imgs.append(img_out)
    return np.array(out_imgs)

In [ ]:
train_data_paths_1d = np.concatenate(train_data_paths, axis=0)

In [ ]:
train_x_299[0] = myResize(train_x[3210], 299)

In [35]:
test_img = train_x[0]
test_img.shape

TensorShape([72, 72, 3])

In [36]:
src = test_img
dst = cv2.resize(src, dsize=(299,299), interpolation=cv2.INTER_LINEAR)

TypeError: Expected Ptr<cv::UMat> for argument 'src'

In [44]:
dst.shape

(299, 299, 3)

In [45]:
dst = dst[tf.newaxis,...]

In [46]:
dst.shape

(1, 299, 299, 3)

In [47]:
pred = model.predict(dst)

In [49]:
pred, np.argmax(pred)

(array([[7.66935885e-01, 5.25051029e-04, 7.55067822e-03, 8.90510809e-03,
         5.58580272e-04, 1.06354982e-01, 1.59451179e-03, 2.32675555e-03,
         3.94300805e-05, 3.18907027e-04, 3.65137414e-04, 4.55302288e-05,
         2.20304762e-04, 5.97007747e-04, 6.26780326e-04, 4.88083460e-05,
         4.93262371e-04, 1.71152700e-04, 4.03835838e-05, 4.98136990e-02,
         6.29436909e-05, 3.49576439e-04, 9.45427164e-04, 3.11451126e-03,
         7.99903122e-04, 3.44519154e-04, 3.55910917e-04, 2.82821478e-04,
         1.24881808e-02, 1.06430358e-04, 1.52574070e-02, 3.83575819e-03,
         1.92344817e-03, 7.33965833e-04, 9.60690595e-05, 5.19359492e-05,
         5.19428123e-03, 3.47270747e-04, 1.48882436e-05, 6.61238955e-05,
         1.53653848e-03, 1.29268752e-04, 5.57339925e-04, 9.86349769e-05,
         1.42270641e-04, 7.72720159e-05, 8.07956036e-04, 1.77050068e-03,
         8.47323463e-06, 5.62017201e-04, 1.60639843e-07, 2.08712137e-07,
         3.29222303e-07, 1.84878203e-07, 1.29792326

In [36]:
test.shape

(1, 72, 299, 299)

In [ ]:
pred = model_xception2.predict(test_)

In [31]:
test.shape

(1, 72, 299, 299)

In [ ]:
pred, np.argmax(pred)

In [ ]:
plt.imshow(test_x_64[index])
plt.colorbar()
plt.show()

In [ ]:
train_x[1]_4d = train_x[1][...,tf.newaxis]

In [ ]:
confirm[300].shape

In [26]:
pred = model.predict(train_x[0].reshape(1,299,299,3))
pred

ValueError: cannot reshape array of size 15552 into shape (1,299,299,3)

In [ ]:
confirm[9999]

In [ ]:
pred = model.predict(test_x[9999].reshape(1,32,32,3))
pred, np.argmax(pred), test_y[9999]

In [26]:
save_path = 'pleaseon.h5'
model.save(save_path, include_optimizer=True)

In [1]:
new_read = tf.keras.models.load_model(pleaseon.h5)

NameError: name 'tf' is not defined

In [4]:
save_path = 'pleaseon.h5'

In [5]:
model_new_read = tf.keras.models.load_model(save_path)

In [6]:
model_new_read.summary()

Model: "xception"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 299, 299, 3) 0                                            
__________________________________________________________________________________________________
block1_conv1 (Conv2D)           (None, 149, 149, 32) 864         input_1[0][0]                    
__________________________________________________________________________________________________
block1_conv1_bn (BatchNormaliza (None, 149, 149, 32) 128         block1_conv1[0][0]               
__________________________________________________________________________________________________
block1_conv1_act (Activation)   (None, 149, 149, 32) 0           block1_conv1_bn[0][0]            
___________________________________________________________________________________________

In [24]:
test_img = train_x[321]

In [34]:
test_img = train_x[0]
test_img.shape

TensorShape([72, 72, 3])

In [28]:
test_img = test_img[tf.newaxis,...]

In [29]:
pred = model_new_read.predict(test_img)

In [30]:
pred, np.argmax(pred)

(array([[5.92735469e-01, 1.02861736e-06, 1.45709532e-06, 5.58637930e-06,
         1.30067247e-06, 2.67156726e-03, 4.11800045e-07, 1.34720676e-05,
         2.31271329e-07, 1.73660408e-06, 1.64906260e-06, 9.12987343e-06,
         4.59185903e-05, 1.47295278e-08, 7.35439414e-07, 9.60882194e-03,
         1.36372819e-07, 4.53020647e-07, 9.72135439e-09, 6.73945251e-05,
         3.16116302e-06, 4.52330823e-05, 4.96133871e-05, 8.95439086e-07,
         3.94399822e-01, 2.45272645e-07, 1.44540390e-05, 8.15442220e-08,
         6.73769762e-07, 1.02751733e-06, 5.60089175e-05, 2.62798551e-07,
         6.22264315e-06, 1.46381426e-04, 6.88964792e-05, 2.13068194e-08,
         9.97125994e-07, 3.15058278e-05, 1.19786527e-08, 1.02382662e-08,
         1.66647609e-07, 1.34584283e-07, 3.23555838e-07, 7.99307657e-07,
         2.66911684e-08, 1.23223820e-09, 3.41007620e-07, 5.94359608e-06,
         7.65496679e-08, 5.81203423e-08, 8.47554943e-11, 7.04814540e-10,
         6.53008828e-11, 3.52698079e-11, 8.19175283